#!/bin/bash

localfile=`echo $1 | sed 's/^.*\/\([^\/]*\)$/\1/'`
if [ -f $localfile ] ; then 
  rm $localfile
fi
scp "$1" .
if [ `echo $localfile | grep -c '\.pdf\.gz'` == "1" ] ; then
   gunzip -f "$localfile"
   localfile=`echo $localfile | sed 's/\.gz//'`
fi
open -a preview "$localfile"
