#!/bin/bash

if [ "x" != "x$1" ] ; then
   if [ "x" != "x$2" ] ; then
      if [ $1 -le $2 ] ; then
         for((i=$1; i<=$2; i++)); do echo $i; done
      else
         for((i=$1; i>=$2; i--)); do echo $i; done
      fi
   else
      echo $1
   fi  
fi
